#!/usr/bin/env python3
"""
Visualize poses generated by HalfSphereRecordingAgent and visualize the viewing direction
(pose -> base).

No local copies of quat / pose generation logic: everything is taken from the agent.
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial.transform import Rotation

from franka_pipeline.agents.half_sphere_recording_agent import HalfSphereRecordingAgent


def plot_poses(poses: np.ndarray, dirs: np.ndarray, base_point: np.ndarray):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection="3d")

    pts = poses[:, :3]
    ax.scatter(pts[:, 0], pts[:, 1], pts[:, 2], s=40, label="poses")
    ax.scatter([base_point[0]], [base_point[1]], [base_point[2]], s=80, marker="x", label="base")

    # draw order numbers
    for i, (x, y, z) in enumerate(pts):
        ax.text(x, y, z, str(i), fontsize=9)

    arrow_len = 0.06
    dnorm = np.linalg.norm(dirs, axis=1, keepdims=True)
    dunit = dirs / np.maximum(dnorm, 1e-12)

    ax.quiver(
        pts[:, 0], pts[:, 1], pts[:, 2],
        dunit[:, 0], dunit[:, 1], dunit[:, 2],
        length=arrow_len,
        normalize=True,
        linewidth=1.5,
        color="k",
        label="view dir (to base)",
    )

    draw_axes = True
    if draw_axes:
        axis_len = 0.04
        for i in range(len(poses)):
            q = poses[i, 3:7]
            Rm = Rotation.from_quat(q).as_matrix()
            x_axis = Rm[:, 0]
            y_axis = Rm[:, 1]
            z_axis = Rm[:, 2]
            p = pts[i]

            ax.quiver(p[0], p[1], p[2], x_axis[0], x_axis[1], x_axis[2],
                      length=axis_len, normalize=True, color="r", linewidth=1.0)
            ax.quiver(p[0], p[1], p[2], y_axis[0], y_axis[1], y_axis[2],
                      length=axis_len, normalize=True, color="g", linewidth=1.0)
            ax.quiver(p[0], p[1], p[2], z_axis[0], z_axis[1], z_axis[2],
                      length=axis_len, normalize=True, color="b", linewidth=1.0)

    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Z")

    mins = pts.min(axis=0)
    maxs = pts.max(axis=0)
    center = 0.5 * (mins + maxs)
    span = (maxs - mins).max()
    half = 0.5 * span if span > 0 else 1.0
    ax.set_xlim(center[0] - half, center[0] + half)
    ax.set_ylim(center[1] - half, center[1] + half)
    ax.set_zlim(center[2] - half, center[2] + half)

    ax.legend()
    plt.tight_layout()
    plt.show()


def main():
    # Create the agent so we use its exact methods and defaults
    agent = HalfSphereRecordingAgent(wait_time=0.0)

    # Option A (simplest): use the poses the agent already generated in __init__
    poses = np.asarray(agent.poses, dtype=float)

    # If you want to regenerate with custom parameters, use Option B instead:
    # base_pose = np.array([0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], dtype=float)
    # radius = 0.1
    # poses = np.asarray(
    #     agent.generate_hemisphere_poses(
    #         base_pose=base_pose,
    #         radius=radius,
    #         num_theta=4,
    #         num_phi=7,
    #         use_quat="keep_y_horizontal",
    #         filter_p_gt=-1,
    #         dx_min=-radius / 5.0,
    #     ),
    #     dtype=float,
    # )

    base_point = poses[0, :3] * 0.0  # placeholder, overwritten below

    # IMPORTANT: dirs should be "base_point - pose_position" like in the agent
    # base_point is the translation of the base pose used for generation.
    # If you used Option A, you need the base_pose the agent used.
    # Your agent currently hardcodes base_pose in __init__ (recommended: store it).
    #
    # Minimal fix without changing agent: re-declare the same base_pose here:
    base_pose = np.array([0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], dtype=float)
    base_point = base_pose[:3].copy()

    dirs = base_point[None, :] - poses[:, :3]

    print(f"Generated {len(poses)} poses [x,y,z,qx,qy,qz,qw]:")
    np.set_printoptions(precision=6, suppress=True)
    print(poses)

    plot_poses(poses, dirs, base_point)


if __name__ == "__main__":
    main()
