#!/usr/bin/env python3

"""Visualize poses generated by different agents, or load them from a .npy file.

Usage:
    python visualize_agent_poses.py                                  # Default: RandomHemisphereAgent
    python visualize_agent_poses.py --agent hemisphere               # HemisphereGridAgent
    python visualize_agent_poses.py --agent random_hemisphere --num-poses 30
    python visualize_agent_poses.py --agent random_hemisphere --seed 42
    python visualize_agent_poses.py --file calibration_poses.npy     # Load stored poses
    python visualize_agent_poses.py --file manual_poses.npy --target 0.4 0.0 0.2
"""

import argparse
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial.transform import Rotation

from franka_pipeline.agents.hemisphere_grid_agent import HemisphereGridAgent
from franka_pipeline.agents.random_hemisphere_agent import RandomHemisphereAgent
import config_defaults as cfg


def plot_poses(
    poses: np.ndarray,
    target_point: np.ndarray,
    title: str = "Agent Poses",
    show_axes: bool = True,
    show_view_dirs: bool = True,
    sphere_center: np.ndarray = None,
    sphere_radius: float = None,
):
    """
    Plot 3D visualization of agent poses.
    
    Args:
        poses: Array of shape (N, 7) with [x, y, z, qx, qy, qz, qw] per pose
        target_point: The point the camera is looking at (e.g., object position)
        title: Plot title
        show_axes: If True, draw coordinate axes for each pose
        show_view_dirs: If True, draw arrows showing viewing direction
        sphere_center: Center of the sampling sphere (optional, for visualization)
        sphere_radius: Radius of the sampling sphere (optional, for visualization)
    """
    fig = plt.figure(figsize=(12, 10))
    ax = fig.add_subplot(111, projection="3d")

    pts = poses[:, :3]
    
    # Plot pose positions
    ax.scatter(pts[:, 0], pts[:, 1], pts[:, 2], s=50, c='blue', label="Camera poses")
    
    # Plot target point (object location)
    ax.scatter(
        [target_point[0]], [target_point[1]], [target_point[2]],
        s=150, marker="*", c='red', label="Target (object)"
    )
    
    # Plot sphere center if different from target
    if sphere_center is not None and not np.allclose(sphere_center, target_point):
        ax.scatter(
            [sphere_center[0]], [sphere_center[1]], [sphere_center[2]],
            s=100, marker="o", c='orange', label="Sphere center"
        )
        
        # Draw wireframe sphere
        if sphere_radius is not None:
            u = np.linspace(0, 2 * np.pi, 20)
            v = np.linspace(0, np.pi, 15)
            x = sphere_center[0] + sphere_radius * np.outer(np.cos(u), np.sin(v))
            y = sphere_center[1] + sphere_radius * np.outer(np.sin(u), np.sin(v))
            z = sphere_center[2] + sphere_radius * np.outer(np.ones(np.size(u)), np.cos(v))
            ax.plot_wireframe(x, y, z, color='orange', alpha=0.1, linewidth=0.5)

    # Draw order numbers
    for i, (x, y, z) in enumerate(pts):
        ax.text(x, y, z, str(i), fontsize=8, color='darkblue')

    # Draw viewing directions (pose -> target)
    if show_view_dirs:
        dirs = target_point[None, :] - pts
        dnorm = np.linalg.norm(dirs, axis=1, keepdims=True)
        dunit = dirs / np.maximum(dnorm, 1e-12)
        
        arrow_len = 0.06
        ax.quiver(
            pts[:, 0], pts[:, 1], pts[:, 2],
            dunit[:, 0], dunit[:, 1], dunit[:, 2],
            length=arrow_len,
            normalize=True,
            linewidth=1.5,
            color="black",
            alpha=0.7,
            label="View direction",
        )

    # Draw coordinate axes for each pose
    if show_axes:
        axis_len = 0.04
        for i in range(len(poses)):
            q = poses[i, 3:7]
            Rm = Rotation.from_quat(q).as_matrix()
            x_axis = Rm[:, 0]
            y_axis = Rm[:, 1]
            z_axis = Rm[:, 2]
            p = pts[i]

            ax.quiver(p[0], p[1], p[2], x_axis[0], x_axis[1], x_axis[2],
                      length=axis_len, normalize=True, color="r", linewidth=1.0, alpha=0.6)
            ax.quiver(p[0], p[1], p[2], y_axis[0], y_axis[1], y_axis[2],
                      length=axis_len, normalize=True, color="g", linewidth=1.0, alpha=0.6)
            ax.quiver(p[0], p[1], p[2], z_axis[0], z_axis[1], z_axis[2],
                      length=axis_len, normalize=True, color="b", linewidth=1.0, alpha=0.6)

    # Draw a small sphere/circle to show the sampling region
    # (for sphere agent, show the sphere boundary)
    
    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Z")
    ax.set_title(title)

    # Set equal aspect ratio
    all_pts = np.vstack([pts, target_point.reshape(1, 3)])
    mins = all_pts.min(axis=0)
    maxs = all_pts.max(axis=0)
    center = 0.5 * (mins + maxs)
    span = (maxs - mins).max()
    half = 0.6 * span if span > 0 else 0.5  # Add some margin
    
    ax.set_xlim(center[0] - half, center[0] + half)
    ax.set_ylim(center[1] - half, center[1] + half)
    ax.set_zlim(center[2] - half, center[2] + half)

    # Add legend
    ax.legend(loc='upper left')
    
    # Add info text
    info_text = f"Total poses: {len(poses)}"
    fig.text(0.02, 0.02, info_text, fontsize=10, family='monospace')
    
    plt.tight_layout()
    plt.show()


def create_hemisphere_agent(args) -> tuple[HemisphereGridAgent, np.ndarray]:
    """Create HemisphereGridAgent and return (agent, target_point)."""
    agent = HemisphereGridAgent(wait_time=0.0)
    
    # The hemisphere agent looks at the base_pose position
    target_point = np.array([cfg.TARGET_X, cfg.TARGET_Y, cfg.TARGET_Z])
    
    return agent, target_point


def create_random_hemisphere_agent(args) -> tuple[RandomHemisphereAgent, np.ndarray]:
    """Create RandomHemisphereAgent and return (agent, target_point).
    
    For RandomHemisphereAgent, the center is always equal to the target point.
    """
    target = np.array(args.target) if args.target else np.array([cfg.TARGET_X, cfg.TARGET_Y, cfg.TARGET_Z])
    # For random_hemisphere, center equals target point
    center = target
    
    agent = RandomHemisphereAgent(
        center=center,
        radius=args.radius,
        inner_radius=args.inner_radius,
        num_poses=args.num_poses,
        wait_time=0.0,
        seed=args.seed,
        loop=False,
        target_point=target,
        base_exclusion_radius=cfg.BASE_EXCLUSION_RADIUS,
        base_max_radius=cfg.BASE_MAX_RADIUS,
        min_z_height=cfg.MIN_Z_HEIGHT,
        lock_rotation_horizontal=cfg.LOCK_ROTATION_HORIZONTAL,
        center_z_offset=args.center_z_offset,
        use_ee_poses=args.ee_poses,
    )
    
    # The hemisphere agent looks at the target point
    target_point = agent.target_point
    
    return agent, target_point


def _poses_from_file(path: str) -> np.ndarray:
    """Load poses from a .npy file.

    Accepts either:
      - (N, 7) arrays  [x, y, z, qx, qy, qz, qw]  (generate_poses.py output)
      - (N, 4, 4) arrays of homogeneous matrices    (record_poses.py output)
    Returns an (N, 7) array in both cases.
    """
    data = np.load(path)
    if data.ndim == 2 and data.shape[1] == 7:
        return data.astype(float)
    if data.ndim == 3 and data.shape[1:] == (4, 4):
        from scipy.spatial.transform import Rotation
        xyzs = data[:, :3, 3]
        quats = Rotation.from_matrix(data[:, :3, :3]).as_quat()  # (N, 4) xyzw
        return np.hstack([xyzs, quats]).astype(float)
    raise ValueError(
        f"Unsupported pose array shape {data.shape}. "
        "Expected (N, 7) or (N, 4, 4)."
    )


def main():
    parser = argparse.ArgumentParser(
        description="Visualize poses generated by different agents",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python visualize_agent_poses.py --agent hemisphere
  python visualize_agent_poses.py --agent random_hemisphere
  python visualize_agent_poses.py --agent random_hemisphere --num-poses 30 --radius 0.25
  python visualize_agent_poses.py --agent random_hemisphere --seed 42
  python visualize_agent_poses.py --file calibration_poses.npy
  python visualize_agent_poses.py --file manual_poses.npy --target 0.4 0.0 0.2
        """
    )
    
    parser.add_argument(
        "--file", "-f",
        type=str,
        default=None,
        metavar="POSES.NPY",
        help="Load poses directly from a .npy file instead of generating them. "
             "Accepts (N,7) [x,y,z,qx,qy,qz,qw] or (N,4,4) homogeneous matrices.",
    )
    parser.add_argument(
        "--agent", "-a",
        type=str,
        default=cfg.AGENT_TYPE,
        choices=["hemisphere", "random_hemisphere"],
        help=f"Agent type to visualize (ignored when --file is used, default: {cfg.AGENT_TYPE})"
    )
    
    # Agent parameters
    parser.add_argument(
        "--center",
        type=float,
        nargs=3,
        default=None,
        metavar=("X", "Y", "Z"),
        help=f"Center [x, y, z] (default: same as target for random_hemisphere)"
    )
    parser.add_argument(
        "--target",
        type=float,
        nargs=3,
        default=None,
        metavar=("X", "Y", "Z"),
        help=f"Target point the camera looks at [x, y, z] (default: {cfg.TARGET_X} {cfg.TARGET_Y} {cfg.TARGET_Z})"
    )
    parser.add_argument(
        "--radius",
        type=float,
        default=cfg.SPHERE_RADIUS,
        help=f"Sphere radius (default: {cfg.SPHERE_RADIUS})"
    )
    parser.add_argument(
        "--inner-radius",
        type=float,
        default=cfg.INNER_RADIUS,
        help=f"Inner radius to exclude for random_hemisphere (default: {cfg.INNER_RADIUS})"
    )
    parser.add_argument(
        "--center-z-offset",
        type=float,
        default=cfg.CENTER_Z_OFFSET,
        help=f"Z offset added to the hemisphere center only (target point unchanged, default: {cfg.CENTER_Z_OFFSET})"
    )
    parser.add_argument(
        "--num-poses",
        type=int,
        default=cfg.NUM_POSES,
        help=f"Number of poses to generate (default: {cfg.NUM_POSES})"
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=cfg.RANDOM_SEED,
        help="Random seed for reproducibility"
    )
    parser.add_argument(
        "--ee-poses",
        action="store_true",
        default=False,
        help="EE pose mode: sample hemisphere as EE positions and point the EE z-axis at "
             "the target (no camera calibration needed). Use --target to set the EE target point.",
    )
    
    # Visualization options
    parser.add_argument(
        "--no-axes",
        action="store_true",
        help="Don't show coordinate axes at each pose"
    )
    parser.add_argument(
        "--no-view-dirs",
        action="store_true",
        help="Don't show viewing direction arrows"
    )
    
    args = parser.parse_args()
    
    # Load or generate poses
    sphere_center = None
    sphere_radius = None

    if args.file is not None:
        poses = _poses_from_file(args.file)
        target_point = np.array(args.target) if args.target else np.array([cfg.TARGET_X, cfg.TARGET_Y, cfg.TARGET_Z])
        title = f"Poses from {args.file}"
        print(f"File:        {args.file}")
        print(f"Loaded {len(poses)} poses")
    else:
        if args.agent == "hemisphere":
            agent, target_point = create_hemisphere_agent(args)
            title = "HemisphereGridAgent Poses"
        elif args.agent == "random_hemisphere":
            agent, target_point = create_random_hemisphere_agent(args)
            title = f"RandomHemisphereAgent Poses (r={args.radius}, inner={args.inner_radius}, n={args.num_poses})"
            sphere_center = agent.center
            sphere_radius = agent.radius
        else:
            raise ValueError(f"Unknown agent type: {args.agent}")
        poses = np.asarray(agent.poses, dtype=float)
        print(f"Agent: {args.agent}")
        print(f"Generated {len(poses)} poses")
    print(f"Target point: {target_point}")
    if sphere_center is not None:
        print(f"Sphere center: {sphere_center}")
        print(f"Sphere radius: {sphere_radius}")
    print()
    
    np.set_printoptions(precision=4, suppress=True)
    print("Poses [x, y, z, qx, qy, qz, qw]:")
    for i, pose in enumerate(poses):
        print(f"  {i:2d}: {pose}")
    
    # Plot
    plot_poses(
        poses=poses,
        target_point=target_point,
        title=title,
        show_axes=not args.no_axes,
        show_view_dirs=not args.no_view_dirs,
        sphere_center=sphere_center,
        sphere_radius=sphere_radius,
    )


if __name__ == "__main__":
    main()
